-- Table: bronze.studentexport_raw
-- Purpose: raw copy of studentexport.csv; all columns TEXT; source_row is 0-based pandas index

CREATE TABLE IF NOT EXISTS bronze.studentexport_raw (
    id                                 SERIAL PRIMARY KEY,
    source_row                         INTEGER NOT NULL,
    row_number                         TEXT,
    name                               TEXT,
    email                              TEXT,
    registration_number                TEXT,
    contact_number_dial_code           TEXT,
    contact_number                     TEXT,
    alternate_contact_number_dial_code TEXT,
    alternate_contact_number           TEXT,
    date_of_birth                      TEXT,
    parent_name                        TEXT,
    parent_contact                     TEXT,
    parent_email                       TEXT,
    address                            TEXT,
    city                               TEXT,
    state                              TEXT,
    standard                           TEXT,
    date_created                       TEXT,
    username                           TEXT,
    gender                             TEXT,
    status                             TEXT,
    username_1                         TEXT,
    why_study_sanskrit                 TEXT,
    user_nice_name                     TEXT,
    user_last_name                     TEXT,
    would_like_to_teach                TEXT,
    teaching_experience                TEXT,
    is_mainstream_education            TEXT,
    objective                          TEXT,
    user_age                           TEXT,
    persona                            TEXT,
    objective_package                  TEXT,
    time_per_week_hours                TEXT,
    age_                               TEXT,
    facebook_profile_url               TEXT,
    instagram_profile_url              TEXT,
    pinterest_profile_url              TEXT,
    soundcloud_profile_url             TEXT,
    tumblr_profile_url                 TEXT,
    youtube_profile_url                TEXT,
    wikipedia_url                      TEXT,
    twitter_username                   TEXT,
    gst_number                         TEXT,
    myspace_profile_url                TEXT,
    international_phone_number         TEXT,
    website                            TEXT,
    educational_qualification          TEXT,
    linkedin_profile_url               TEXT,
    age_v2                             TEXT,
    gender_                            TEXT,
    sanskrit_qualification             TEXT,
    areas_of_interest                  TEXT,
    studying_sanskrit_currently        TEXT,
    current_education_status           TEXT,
    country_name                       TEXT,
    loaded_at                          TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (source_row)
);
