-- Table: bronze.course_catalogue_raw
-- Purpose: raw copy of course_catalogue_data.csv; all 59 columns stored as TEXT; one-time historical load

CREATE TABLE IF NOT EXISTS bronze.course_catalogue_raw (
    id                               SERIAL PRIMARY KEY,
    source_row                       INTEGER NOT NULL,
    bundle_id                        TEXT,
    course_name                      TEXT,
    course_description               TEXT,
    overview                         TEXT,
    cost                             TEXT,
    is_online_package                TEXT,
    online_registration_allowed      TEXT,
    free_preview_allowed             TEXT,
    pretty_name                      TEXT,
    num_students                     TEXT,
    tutors                           TEXT,
    tutord_ids                       TEXT,
    course_url                       TEXT,
    course_list                      TEXT,
    course_ids                       TEXT,
    subject                          TEXT,
    level                            TEXT,
    language                         TEXT,
    examination                      TEXT,
    texts                            TEXT,
    type                             TEXT,
    course_division                  TEXT,
    certificate                      TEXT,
    course_sponsor                   TEXT,
    course_title_sanskrit            TEXT,
    duration_old                     TEXT,
    live_session_schedule_text       TEXT,
    about_the_course                 TEXT,
    know_more_about_the_course       TEXT,
    about_this_learning_program      TEXT,
    learning_program_value_proposi   TEXT,
    how_learning_program_works       TEXT,
    know_more_about_the_programs     TEXT,
    coming_soon                      TEXT,
    target_audience                  TEXT,
    status                           TEXT,
    number_of_lectures               TEXT,
    duration                         TEXT,
    personas                         TEXT,
    ongoing_webinar_note             TEXT,
    eligibility                      TEXT,
    whats_new                        TEXT,
    whats_new_poster                 TEXT,
    meta_title                       TEXT,
    meta_description                 TEXT,
    meta_keywords                    TEXT,
    dsg_link                         TEXT,
    hide_in_ongoing_webinar          TEXT,
    computer_based_assessment        TEXT,
    course_ordering                  TEXT,
    post_enrollment_redirect_url     TEXT,
    product_id                       TEXT,
    sss_category                     TEXT,
    credits                          TEXT,
    viniyoga                         TEXT,
    adhyayanam_category              TEXT,
    term_of_course                   TEXT,
    position_in_funnel               TEXT,
    division                         TEXT,
    loaded_at                        TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (source_row)
);
